<!DOCTYPE html>
<html lang="en"><head>
<script src="2026-10-07-reach-ps-survival_files/libs/clipboard/clipboard.min.js"></script>
<script src="2026-10-07-reach-ps-survival_files/libs/quarto-html/tabby.min.js"></script>
<script src="2026-10-07-reach-ps-survival_files/libs/quarto-html/popper.min.js"></script>
<script src="2026-10-07-reach-ps-survival_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="2026-10-07-reach-ps-survival_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2026-10-07-reach-ps-survival_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="2026-10-07-reach-ps-survival_files/libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Erik Westlund">
  <meta name="dcterms.date" content="2026-10-07">
  <title>REACH and RStudio: PS and Survival Analysis</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="2026-10-07-reach-ps-survival_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="2026-10-07-reach-ps-survival_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="2026-10-07-reach-ps-survival_files/libs/revealjs/dist/theme/quarto-af29b85d7f601797026d66e86459ea4d.css">
  <link href="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">REACH and RStudio: PS and Survival Analysis</h1>
  <p class="subtitle">Basics of OHDSI Study Design &amp; Statistical Analysis</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Erik Westlund 
</div>
</div>
</div>

  <p class="date">2026-10-07</p>
</section>
<section>
<section id="welcome" class="title-slide slide level1 center">
<h1>Welcome</h1>

</section>
<section id="course-materials" class="slide level2">
<h2>Course Materials</h2>
<p>The slides and the code behind every example are available on GitHub at <a href="https://github.com/erikwestlund/2026-bids-bootcamp">github.com/erikwestlund/2026-bids-bootcamp</a>.</p>
</section>
<section id="todays-plan" class="slide level2">
<h2>Today’s Plan</h2>
<ol type="1">
<li>Study design and causal inference</li>
<li>Common types of research outcomes in OHDSI</li>
<li>Confounding and approaches to addressing it</li>
<li>A preview of propensity scores and CohortMethod</li>
</ol>
<div class="fragment">
<p>On Monday we described cohorts with tables and figures. Today and Friday we move from description to estimation: measuring the effect of a treatment on an outcome.</p>
</div>
</section></section>
<section>
<section id="before-we-model" class="title-slide slide level1 center">
<h1>Before We Model</h1>

</section>
<section id="design-comes-first" class="slide level2">
<h2>Design Comes First</h2>
<p>Aki’s lecture covered the basics of study design and causal inference. In the next sections, we will introduce the basic statistical machinery used in OHDSI to execute OHDSI studies.</p>
<p>Before choosing a model, a study needs answers to several questions:</p>
<ul>
<li>What is the research question?</li>
<li>Which groups are being compared?</li>
<li>What is the outcome?</li>
<li>Over what period of time will it be measured?</li>
</ul>
<div class="fragment">
<p>A statistical model cannot fix what is spoiled by design.</p>
</div>
</section>
<section id="directed-acyclic-graphs" class="slide level2">
<h2>Directed Acyclic Graphs</h2>
<p>A directed acyclic graph (DAG) is a picture of the causal relationships we assume. Each box is a variable, and each arrow means “affects”. The graph is acyclic because no variable can loop back and cause itself.</p>
<ul>
<li>A path from treatment to outcome that follows the arrows forward is the causal effect we want to estimate.</li>
<li>A <strong>backdoor path</strong> is any other path that connects treatment and outcome through an arrow pointing <em>into</em> treatment. Backdoor paths create associations between treatment and outcome that are not caused by the treatment.</li>
<li>A study estimates the causal effect once every backdoor path is blocked, either by design or by adjusting for the right variables.</li>
</ul>
</section>
<section id="further-readingviewing-on-design-causal-inference-dags" class="slide level2">
<h2>Further Reading/Viewing on Design, Causal Inference, &amp; DAGs</h2>
<p>These are great resources on causal inference, design, and DAGS:</p>
<ul>
<li>Morgan, S. L., and Winship, C. (2015). <em>Counterfactuals and Causal Inference: Methods and Principles for Social Research</em> (2nd ed.). Cambridge University Press.</li>
<li>Pearl, J. (2009). <em>Causality: Models, Reasoning, and Inference</em> (2nd ed.). Cambridge University Press.</li>
<li>Pearl, J., Glymour, M., and Jewell, N. P. (2016). <em>Causal Inference in Statistics: A Primer</em>. Wiley.</li>
<li>Richard McElreath’s <em>Statistical Rethinking</em> course, whose lectures and materials are freely available online at <a href="https://github.com/rmcelreath">github.com/rmcelreath</a>.</li>
</ul>
</section>
<section id="an-example-dag" class="slide level2">
<h2>An Example DAG</h2>
<p>Suppose we compare celecoxib with a traditional NSAID and measure the risk of a GI bleed. Celecoxib is often chosen for patients with a history of ulcers, and those patients are also more likely to bleed.</p>

<img data-src="2026-10-07-reach-ps-survival_files/figure-revealjs/dag-celecoxib-1.png" width="960" class="r-stretch"><p>The arrow from celecoxib to GI bleed is the effect we want. The following path is a backdoor path:</p>
<div style="text-align: center;">
<p>celecoxib ← prior ulcer → GI bleed</p>
</div>
<p>Unless we adjust for prior ulcers, it would make celecoxib look more harmful than it is.</p>
</section>
<section id="why-randomized-trials-work" class="slide level2">
<h2>Why Randomized Trials Work</h2>
<ul>
<li>In a randomized controlled trial, chance alone decides who receives the treatment.</li>
<li>As a result, the treated and untreated groups are expected to be the same at baseline in every respect, measured or not.</li>
<li>Any systematic difference in outcomes between the groups can therefore be attributed to the treatment.</li>
</ul>
</section>
<section id="the-structure-of-a-trial" class="slide level2">
<h2>The Structure of a Trial</h2>
<p>In a trial, randomization is the only cause of treatment. Other causes of the outcome, such as age and sex, have no arrow into treatment.</p>

<img data-src="2026-10-07-reach-ps-survival_files/figure-revealjs/dag-trial-1.png" width="960" class="r-stretch"><p>Because nothing else points into treatment, the only path from treatment to outcome is the direct one, and a simple comparison of the two groups estimates the treatment effect.</p>
</section>
<section id="observational-data" class="slide level2">
<h2>Observational Data</h2>
<p>In observational data, treatment is not assigned at random. Doctors and patients choose treatments for various reasons, from the state of evidence to limitations of insurance and the health system.</p>
<p>A <strong>confounder</strong> is a variable that affects both which treatment a person receives and the outcome.</p>
</section>
<section id="the-structure-of-confounding" class="slide level2">
<h2>The Structure of Confounding</h2>
<p>In observational data, a confounder adds an arrow into treatment.</p>

<img data-src="2026-10-07-reach-ps-survival_files/figure-revealjs/dag-confounder-1.png" width="960" class="r-stretch"><p>The confounder opens a backdoor path from treatment to outcome. Comparing treated and untreated patients without accounting for it mixes the two paths together, biasing the estimated effect size of the treatment.</p>
</section>
<section id="confounding-by-age-and-sex" class="slide level2">
<h2>Confounding by Age and Sex</h2>
<p>In today’s simulations, older patients and men are more likely to be treated. They are also more likely to have worse outcomes.</p>

<img data-src="2026-10-07-reach-ps-survival_files/figure-revealjs/dag-1.png" width="960" class="r-stretch"><p>A comparison of treated and untreated patients that ignores age and sex mixes the effect of the treatment with the effects of age and sex.</p>
</section></section>
<section>
<section id="different-research-outcomes-different-models" class="title-slide slide level1 center">
<h1>Different Research Outcomes, Different Models</h1>

</section>
<section id="four-common-models" class="slide level2">
<h2>Four Common Models</h2>
<p>The right model depends on the type of outcome being studied.</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Outcome</th>
<th>Example</th>
<th>Model</th>
<th>Treatment effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Continuous</td>
<td>Blood pressure</td>
<td>Linear (OLS)</td>
<td>Difference in mean outcome</td>
</tr>
<tr class="even">
<td>Binary</td>
<td>GI bleed</td>
<td>Logistic</td>
<td>Odds ratio</td>
</tr>
<tr class="odd">
<td>Count or rate</td>
<td>Number of ER visits</td>
<td>Poisson</td>
<td>Rate ratio</td>
</tr>
<tr class="even">
<td>Time to event</td>
<td>Time until GI bleed</td>
<td>Cox</td>
<td>Hazard ratio</td>
</tr>
</tbody>
</table>
</section>
<section id="conditional-effects" class="slide level2">
<h2>Conditional Effects</h2>
<p>Each treatment effect is conditional on the other covariates in the model. It compares treated and untreated patients who have the same values of those covariates. You will often read statements like “all else equal” or “controlling for” to convey how covariates are adjusted.</p>
</section>
<section id="learning-with-simulation" class="slide level2">
<h2>Learning With Simulation</h2>
<ul>
<li>In a simulation, we choose the true effect of the treatment before generating the data.</li>
<li>We can then check whether a method recovers that effect.</li>
<li>Testing a method on simulated data shows how it behaves before we trust it on real data, where the true effect is unknown.</li>
<li>I find this helps build understanding of how confounding actually works.</li>
</ul>
</section>
<section id="two-simulated-datasets" class="slide level2">
<h2>Two Simulated Datasets</h2>
<p>We build two datasets of 10,000 patients each and reuse them for every model.</p>
<ul>
<li><strong><code>trial</code></strong>: a randomized trial. A coin flip decides treatment.</li>
<li><strong><code>obs</code></strong>: observational data. Age and sex affect both treatment and the outcome.</li>
</ul>
<div class="fragment">
<p>For each model, we add an outcome with a known treatment effect to both datasets. We then check whether the model recovers that effect.</p>
</div>
</section></section>
<section>
<section id="linear-regression" class="title-slide slide level1 center">
<h1>Linear Regression</h1>

</section>
<section id="linear-regression-ols" class="slide level2">
<h2>Linear Regression (OLS)</h2>
<p>Linear regression models a continuous outcome as a straight-line function of the predictors.</p>
<ul>
<li>The <strong>intercept</strong> is the expected outcome when every predictor is zero.</li>
<li>The <strong>coefficient</strong> on treatment is the expected difference in the outcome between treated and untreated patients who have the same values of the other predictors.</li>
</ul>
<div class="fragment">
<p>In the simulation, the outcome is systolic blood pressure, and the treatment lowers it by 5 mmHg.</p>
</div>
</section>
<section id="simulating-a-randomized-trial" class="slide level2">
<h2>Simulating a Randomized Trial</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">21</span>)</span>
<span id="cb1-2"><a href="" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb1-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># A coin flip assigns treatment: 1 = treated, 0 = untreated</span></span>
<span id="cb1-5"><a href="" aria-hidden="true" tabindex="-1"></a>trial <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">treated =</span> <span class="fu">rbinom</span>(n, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fl">0.5</span>))</span>
<span id="cb1-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Blood pressure averages 140; treatment lowers it by 5; rnorm() adds noise</span></span>
<span id="cb1-8"><a href="" aria-hidden="true" tabindex="-1"></a>trial<span class="sc">$</span>sbp <span class="ot">&lt;-</span> <span class="dv">140</span> <span class="sc">-</span> <span class="dv">5</span> <span class="sc">*</span> trial<span class="sc">$</span>treated <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb1-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(trial, <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treated      sbp
1       1 121.4889
2       0 131.8583
3       1 137.8211
4       0 139.7353</code></pre>
</div>
</div>
</section>
<section id="comparing-the-two-groups" class="slide level2">
<h2>Comparing the Two Groups</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(trial, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(treated), <span class="at">y =</span> sbp)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.08</span>, <span class="at">color =</span> <span class="st">"#68ACE5"</span>) <span class="sc">+</span></span>
<span id="cb3-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"#002D72"</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Untreated"</span>, <span class="st">"Treated"</span>)) <span class="sc">+</span></span>
<span id="cb3-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Systolic blood pressure (mmHg)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="2026-10-07-reach-ps-survival_files/figure-revealjs/plot-trial-sbp-1.png" width="960" class="r-stretch"><p>The dark points mark each group’s mean.</p>
</section>
<section id="fitting-the-model" class="slide level2">
<h2>Fitting the Model</h2>
<p><code>lm()</code> fits a linear regression. <code>coef()</code> returns the estimates, and <code>confint()</code> returns their 95% confidence intervals.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="" aria-hidden="true" tabindex="-1"></a>fit_ols_trial <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> treated, <span class="at">data =</span> trial)</span>
<span id="cb4-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">estimate =</span> <span class="fu">coef</span>(fit_ols_trial), <span class="fu">confint</span>(fit_ols_trial)), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            estimate  2.5 % 97.5 %
(Intercept)   140.19 139.91 140.47
treated        -5.13  -5.52  -4.74</code></pre>
</div>
</div>
<div class="fragment">
<p>The coefficient on <code>treated</code> is close to the true effect of −5. With a single binary predictor, it equals the difference between the two group means:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(sbp <span class="sc">~</span> treated, <span class="at">data =</span> trial, <span class="at">FUN =</span> mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treated      sbp
1       0 140.1890
2       1 135.0591</code></pre>
</div>
</div>
</div>
</section>
<section id="simulating-observational-data" class="slide level2">
<h2>Simulating Observational Data</h2>
<p>Now treatment depends on age and sex. <code>plogis()</code> converts a score into a probability between 0 and 1.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb8-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">60</span>, <span class="at">sd =</span> <span class="dv">10</span>),</span>
<span id="cb8-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="at">male =</span> <span class="fu">rbinom</span>(n, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fl">0.5</span>)</span>
<span id="cb8-4"><a href="" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Older patients and men are more likely to be treated</span></span>
<span id="cb8-7"><a href="" aria-hidden="true" tabindex="-1"></a>obs<span class="sc">$</span>treated <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="at">size =</span> <span class="dv">1</span>,</span>
<span id="cb8-8"><a href="" aria-hidden="true" tabindex="-1"></a>                      <span class="at">prob =</span> <span class="fu">plogis</span>(<span class="sc">-</span><span class="fl">1.5</span> <span class="sc">+</span> (obs<span class="sc">$</span>age <span class="sc">-</span> <span class="dv">60</span>) <span class="sc">/</span> <span class="dv">10</span> <span class="sc">+</span> obs<span class="sc">$</span>male))</span>
<span id="cb8-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(<span class="fu">cbind</span>(age, male) <span class="sc">~</span> treated, <span class="at">data =</span> obs, <span class="at">FUN =</span> mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treated      age      male
1       0 57.26718 0.4286973
2       1 65.81325 0.6327170</code></pre>
</div>
</div>
<p>Treated patients are older on average, and a larger share of them are men.</p>
</section>
<section id="a-confounded-outcome" class="slide level2">
<h2>A Confounded Outcome</h2>
<p>Blood pressure rises with age and is higher in men. The treatment effect is still −5. Remember, we simulated the data ourselves, so we know this to be true.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="" aria-hidden="true" tabindex="-1"></a>obs<span class="sc">$</span>sbp <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">+</span> <span class="fl">0.7</span> <span class="sc">*</span> obs<span class="sc">$</span>age <span class="sc">+</span> <span class="dv">4</span> <span class="sc">*</span> obs<span class="sc">$</span>male <span class="sc">-</span> <span class="dv">5</span> <span class="sc">*</span> obs<span class="sc">$</span>treated <span class="sc">+</span></span>
<span id="cb10-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="ignoring-age-and-sex" class="slide level2">
<h2>Ignoring Age and Sex</h2>

<img data-src="2026-10-07-reach-ps-survival_files/figure-revealjs/plot-obs-naive-1.png" width="960" class="r-stretch"><p>The treated group’s mean is <em>higher</em>. Taken at face value, the treatment appears to raise blood pressure.</p>
</section>
<section id="the-same-data-broken-out-by-age-and-sex" class="slide level2">
<h2>The Same Data, Broken Out by Age and Sex</h2>

<img data-src="2026-10-07-reach-ps-survival_files/figure-revealjs/plot-obs-facet-1.png" width="960" class="r-stretch"><p>Within every panel, the treated mean is <em>lower</em>. The treated group looks worse overall only because it is older and has more men.</p>
</section>
<section id="the-unadjusted-model" class="slide level2">
<h2>The Unadjusted Model</h2>
<p>Fitting the model with treatment alone reproduces the misleading comparison.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="" aria-hidden="true" tabindex="-1"></a>fit_ols_naive <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> treated, <span class="at">data =</span> obs)</span>
<span id="cb11-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">estimate =</span> <span class="fu">coef</span>(fit_ols_naive), <span class="fu">confint</span>(fit_ols_naive)), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            estimate  2.5 % 97.5 %
(Intercept)   141.96 141.68 142.25
treated         1.81   1.30   2.31</code></pre>
</div>
</div>
<div class="fragment">
<p>The model estimates an effect of 1.8 mmHg. The true effect is −5.</p>
</div>
</section>
<section id="adjusting-for-age-and-sex" class="slide level2">
<h2>Adjusting for Age and Sex</h2>
<p>Adding age and sex to the model compares treated and untreated patients of the same age and sex.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="" aria-hidden="true" tabindex="-1"></a>fit_ols_adj <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> treated <span class="sc">+</span> age <span class="sc">+</span> male, <span class="at">data =</span> obs)</span>
<span id="cb13-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">estimate =</span> <span class="fu">coef</span>(fit_ols_adj), <span class="fu">confint</span>(fit_ols_adj)), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            estimate 2.5 % 97.5 %
(Intercept)   100.43 99.19 101.66
treated        -4.93 -5.39  -4.46
age             0.70  0.68   0.72
male            3.84  3.44   4.23</code></pre>
</div>
</div>
<div class="fragment">
<p>The adjusted estimate, −4.9 mmHg, is close to the true effect of −5.</p>
</div>
</section></section>
<section>
<section id="logistic-regression" class="title-slide slide level1 center">
<h1>Logistic Regression</h1>

</section>
<section id="logistic-regression-1" class="slide level2">
<h2>Logistic Regression</h2>
<p>Logistic regression models a binary outcome, such as whether a patient has a GI bleed.</p>
<ul>
<li>The <strong>odds</strong> of an event are the probability it happens divided by the probability it does not. A 20% risk is odds of 0.2 / 0.8 = 0.25.</li>
<li>The model estimates coefficients on the <strong>log odds</strong> scale.</li>
<li>Exponentiating a coefficient with <code>exp()</code> gives an <strong>odds ratio</strong>. An odds ratio of 2 means the treatment doubles the odds of the outcome.</li>
</ul>
<div class="fragment">
<p>In the simulation, the treatment doubles the odds of a GI bleed.</p>
</div>
</section>
<section id="logistic-randomized-trial" class="slide level2">
<h2>Logistic: Randomized Trial</h2>
<p><code>rbinom()</code> draws a 0 or 1 for each patient, using the probability from <code>plogis()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="" aria-hidden="true" tabindex="-1"></a>trial<span class="sc">$</span>bleed <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fu">plogis</span>(<span class="sc">-</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">log</span>(<span class="dv">2</span>) <span class="sc">*</span> trial<span class="sc">$</span>treated))</span>
<span id="cb15-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="" aria-hidden="true" tabindex="-1"></a>fit_logit_trial <span class="ot">&lt;-</span> <span class="fu">glm</span>(bleed <span class="sc">~</span> treated, <span class="at">family =</span> binomial, <span class="at">data =</span> trial)</span>
<span id="cb15-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">odds_ratio =</span> <span class="fu">coef</span>(fit_logit_trial), <span class="fu">confint</span>(fit_logit_trial))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            odds_ratio 2.5 % 97.5 %
(Intercept)       0.14  0.13   0.15
treated           1.96  1.76   2.19</code></pre>
</div>
</div>
<div class="fragment">
<p>The odds ratio for <code>treated</code> is close to the true value of 2. The intercept row is the odds of a bleed among untreated patients.</p>
</div>
</section>
<section id="logistic-observational-unadjusted" class="slide level2">
<h2>Logistic: Observational, Unadjusted</h2>
<p>Older patients and men are also more likely to bleed.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="" aria-hidden="true" tabindex="-1"></a>obs<span class="sc">$</span>bleed <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fu">plogis</span>(</span>
<span id="cb17-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">log</span>(<span class="dv">2</span>) <span class="sc">*</span> obs<span class="sc">$</span>treated <span class="sc">+</span> <span class="fl">0.05</span> <span class="sc">*</span> (obs<span class="sc">$</span>age <span class="sc">-</span> <span class="dv">60</span>) <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> obs<span class="sc">$</span>male</span>
<span id="cb17-3"><a href="" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb17-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="" aria-hidden="true" tabindex="-1"></a>fit_logit_naive <span class="ot">&lt;-</span> <span class="fu">glm</span>(bleed <span class="sc">~</span> treated, <span class="at">family =</span> binomial, <span class="at">data =</span> obs)</span>
<span id="cb17-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">odds_ratio =</span> <span class="fu">coef</span>(fit_logit_naive), <span class="fu">confint</span>(fit_logit_naive))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            odds_ratio 2.5 % 97.5 %
(Intercept)       0.15  0.14   0.16
treated           3.61  3.26   3.99</code></pre>
</div>
</div>
<div class="fragment">
<p>The unadjusted odds ratio, 3.61, overstates the harm of the treatment.</p>
</div>
</section>
<section id="logistic-observational-adjusted" class="slide level2">
<h2>Logistic: Observational, Adjusted</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="" aria-hidden="true" tabindex="-1"></a>fit_logit_adj <span class="ot">&lt;-</span> <span class="fu">glm</span>(bleed <span class="sc">~</span> treated <span class="sc">+</span> age <span class="sc">+</span> male, <span class="at">family =</span> binomial, <span class="at">data =</span> obs)</span>
<span id="cb19-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">odds_ratio =</span> <span class="fu">coef</span>(fit_logit_adj), <span class="fu">confint</span>(fit_logit_adj))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            odds_ratio 2.5 % 97.5 %
(Intercept)       0.01  0.00   0.01
treated           2.19  1.96   2.44
age               1.05  1.05   1.06
male              1.81  1.63   2.02</code></pre>
</div>
</div>
<div class="fragment">
<p>After adjustment, the odds ratio for <code>treated</code> is 2.19, close to the true value of 2. The <code>age</code> row is the odds ratio for each additional year of age.</p>
</div>
</section></section>
<section>
<section id="poisson-regression" class="title-slide slide level1 center">
<h1>Poisson Regression</h1>

</section>
<section id="poisson-regression-1" class="slide level2">
<h2>Poisson Regression</h2>
<p>Poisson regression models counts of events, such as the number of ER visits.</p>
<ul>
<li>Patients are followed for different lengths of time. A patient followed for three years has more time to visit the ER than one followed for six months.</li>
<li>The model accounts for this with an <strong>offset</strong>: the log of each patient’s <strong>person-time</strong>.</li>
<li>The model then estimates a <strong>rate</strong>, which for us is often an incidence rate.</li>
<li>Exponentiating a coefficient gives a <strong>rate ratio</strong>.</li>
</ul>
<div class="fragment">
<p>In the simulation, the treatment raises the rate of ER visits by 50%, a rate ratio of 1.5.</p>
</div>
</section>
<section id="poisson-randomized-trial" class="slide level2">
<h2>Poisson: Randomized Trial</h2>
<p>Each patient is followed for between six months and three years. <code>rpois()</code> draws a count of visits from that patient’s rate and follow-up time.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="" aria-hidden="true" tabindex="-1"></a>trial<span class="sc">$</span>years <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="at">min =</span> <span class="fl">0.5</span>, <span class="at">max =</span> <span class="dv">3</span>)</span>
<span id="cb21-2"><a href="" aria-hidden="true" tabindex="-1"></a>trial<span class="sc">$</span>visits <span class="ot">&lt;-</span> <span class="fu">rpois</span>(n, <span class="at">lambda =</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="fl">1.5</span><span class="sc">^</span>trial<span class="sc">$</span>treated <span class="sc">*</span> trial<span class="sc">$</span>years)</span>
<span id="cb21-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="" aria-hidden="true" tabindex="-1"></a>fit_pois_trial <span class="ot">&lt;-</span> <span class="fu">glm</span>(visits <span class="sc">~</span> treated <span class="sc">+</span> <span class="fu">offset</span>(<span class="fu">log</span>(years)),</span>
<span id="cb21-5"><a href="" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family =</span> poisson, <span class="at">data =</span> trial)</span>
<span id="cb21-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">rate_ratio =</span> <span class="fu">coef</span>(fit_pois_trial), <span class="fu">confint</span>(fit_pois_trial))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            rate_ratio 2.5 % 97.5 %
(Intercept)       0.51  0.50   0.53
treated           1.48  1.42   1.53</code></pre>
</div>
</div>
<div class="fragment">
<p>The intercept row is the rate among untreated patients: about 0.5 visits per person-year.</p>
</div>
</section>
<section id="poisson-observational-unadjusted" class="slide level2">
<h2>Poisson: Observational, Unadjusted</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="" aria-hidden="true" tabindex="-1"></a>obs<span class="sc">$</span>years <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="at">min =</span> <span class="fl">0.5</span>, <span class="at">max =</span> <span class="dv">3</span>)</span>
<span id="cb23-2"><a href="" aria-hidden="true" tabindex="-1"></a>obs<span class="sc">$</span>visits <span class="ot">&lt;-</span> <span class="fu">rpois</span>(n, <span class="at">lambda =</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="fl">1.5</span><span class="sc">^</span>obs<span class="sc">$</span>treated <span class="sc">*</span></span>
<span id="cb23-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">exp</span>(<span class="fl">0.03</span> <span class="sc">*</span> (obs<span class="sc">$</span>age <span class="sc">-</span> <span class="dv">60</span>) <span class="sc">+</span> <span class="fl">0.3</span> <span class="sc">*</span> obs<span class="sc">$</span>male) <span class="sc">*</span> obs<span class="sc">$</span>years)</span>
<span id="cb23-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="" aria-hidden="true" tabindex="-1"></a>fit_pois_naive <span class="ot">&lt;-</span> <span class="fu">glm</span>(visits <span class="sc">~</span> treated <span class="sc">+</span> <span class="fu">offset</span>(<span class="fu">log</span>(years)),</span>
<span id="cb23-6"><a href="" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family =</span> poisson, <span class="at">data =</span> obs)</span>
<span id="cb23-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">rate_ratio =</span> <span class="fu">coef</span>(fit_pois_naive), <span class="fu">confint</span>(fit_pois_naive))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            rate_ratio 2.5 % 97.5 %
(Intercept)       0.55  0.54   0.56
treated           2.08  2.01   2.16</code></pre>
</div>
</div>
<div class="fragment">
<p>The unadjusted rate ratio is 2.08. The true value is 1.5.</p>
</div>
</section>
<section id="poisson-observational-adjusted" class="slide level2">
<h2>Poisson: Observational, Adjusted</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="" aria-hidden="true" tabindex="-1"></a>fit_pois_adj <span class="ot">&lt;-</span> <span class="fu">glm</span>(visits <span class="sc">~</span> treated <span class="sc">+</span> age <span class="sc">+</span> male <span class="sc">+</span> <span class="fu">offset</span>(<span class="fu">log</span>(years)),</span>
<span id="cb25-2"><a href="" aria-hidden="true" tabindex="-1"></a>                    <span class="at">family =</span> poisson, <span class="at">data =</span> obs)</span>
<span id="cb25-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">rate_ratio =</span> <span class="fu">coef</span>(fit_pois_adj), <span class="fu">confint</span>(fit_pois_adj))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            rate_ratio 2.5 % 97.5 %
(Intercept)       0.08  0.07   0.09
treated           1.51  1.45   1.57
age               1.03  1.03   1.03
male              1.41  1.36   1.46</code></pre>
</div>
</div>
<div class="fragment">
<p>After adjustment, the rate ratio is 1.51.</p>
</div>
</section></section>
<section>
<section id="survival-analysis" class="title-slide slide level1 center">
<h1>Survival Analysis</h1>

</section>
<section id="survival-analysis-1" class="slide level2">
<h2>Survival Analysis</h2>
<p>Survival analysis models the time until an event occurs.</p>
<ul>
<li>Some patients leave the data before the event can be observed, for example because they change insurance, switch systems, or die. This is called <strong>censoring</strong>. We know only that they had not had the event by the time they left.</li>
<li><strong>Kaplan–Meier curves</strong> show the proportion of each group that is still event-free over time.</li>
<li>The <strong>Cox model</strong> estimates a <strong>hazard ratio</strong>: the ratio of the event rates in the two groups at any point in time.</li>
<li>The Cox model assumes that this ratio is constant over time. This is the <strong>proportional hazards</strong> assumption.</li>
</ul>
<div class="fragment">
<p>In the simulation, the treatment doubles the hazard of a GI bleed.</p>
</div>
</section>
<section id="data-requirements" class="slide level2">
<h2>Data Requirements</h2>
<p>Survival analysis needs one row per patient with at least three pieces of information.</p>
<ul>
<li>A <strong>time zero</strong>, the date follow-up starts. In OHDSI studies this is usually the cohort start date, when the patient begins treatment.</li>
<li>A <strong>follow-up time</strong>, the time from time zero to the event or to the end of follow-up, whichever comes first.</li>
<li>An <strong>event indicator</strong>, which is 1 if the event was observed and 0 if the patient was censored.</li>
</ul>
<div class="fragment">
<p>To compute these, we need the date of the outcome and the date each patient’s follow-up ends, such as the end of their observation period. The Cox model also assumes that censoring is unrelated to the risk of the event once we account for the covariates.</p>
</div>
</section>
<section id="simulating-time-to-event" class="slide level2">
<h2>Simulating Time to Event</h2>
<p><code>rexp()</code> draws each patient’s time to a GI bleed. A second draw sets when each patient leaves the data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="" aria-hidden="true" tabindex="-1"></a>bleed_time <span class="ot">&lt;-</span> <span class="fu">rexp</span>(n, <span class="at">rate =</span> <span class="fl">0.1</span> <span class="sc">*</span> <span class="dv">2</span><span class="sc">^</span>trial<span class="sc">$</span>treated)  <span class="co"># years</span></span>
<span id="cb27-2"><a href="" aria-hidden="true" tabindex="-1"></a>censor_time <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">5</span>)</span>
<span id="cb27-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># We observe whichever comes first</span></span>
<span id="cb27-5"><a href="" aria-hidden="true" tabindex="-1"></a>trial<span class="sc">$</span>time <span class="ot">&lt;-</span> <span class="fu">pmin</span>(bleed_time, censor_time)</span>
<span id="cb27-6"><a href="" aria-hidden="true" tabindex="-1"></a>trial<span class="sc">$</span>event <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(bleed_time <span class="sc">&lt;=</span> censor_time)  <span class="co"># 1 = bleed, 0 = censored</span></span>
<span id="cb27-7"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(trial[, <span class="fu">c</span>(<span class="st">"treated"</span>, <span class="st">"time"</span>, <span class="st">"event"</span>)], <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treated     time event
1       1 1.454757     0
2       0 1.854889     0
3       1 4.374877     0
4       0 1.075882     1</code></pre>
</div>
</div>
</section>
<section id="kaplanmeier-curves" class="slide level2">
<h2>Kaplan–Meier Curves</h2>
<p><code>Surv()</code> combines the follow-up time and the event indicator. <code>survfit()</code> estimates the curves.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="" aria-hidden="true" tabindex="-1"></a>km <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, event) <span class="sc">~</span> treated, <span class="at">data =</span> trial)</span>
<span id="cb29-2"><a href="" aria-hidden="true" tabindex="-1"></a>km_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">time =</span> km<span class="sc">$</span>time, <span class="at">surv =</span> km<span class="sc">$</span>surv,</span>
<span id="cb29-3"><a href="" aria-hidden="true" tabindex="-1"></a>                      <span class="at">group =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Untreated"</span>, <span class="st">"Treated"</span>), km<span class="sc">$</span>strata))</span>
<span id="cb29-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(km_data, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> surv, <span class="at">color =</span> group)) <span class="sc">+</span></span>
<span id="cb29-6"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_step</span>(<span class="at">linewidth =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb29-7"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">Untreated =</span> <span class="st">"#7E7E7C"</span>, <span class="at">Treated =</span> <span class="st">"#002D72"</span>), <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb29-8"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Years since treatment start"</span>, <span class="at">y =</span> <span class="st">"Proportion without a GI bleed"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="2026-10-07-reach-ps-survival_files/figure-revealjs/km-trial-1.png" width="960" class="r-stretch"></section>
<section id="cox-randomized-trial" class="slide level2">
<h2>Cox: Randomized Trial</h2>
<p><code>coxph()</code> fits the Cox model. Its output has no intercept.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="" aria-hidden="true" tabindex="-1"></a>fit_cox_trial <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, event) <span class="sc">~</span> treated, <span class="at">data =</span> trial)</span>
<span id="cb30-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">hazard_ratio =</span> <span class="fu">coef</span>(fit_cox_trial), <span class="fu">confint</span>(fit_cox_trial))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        hazard_ratio 2.5 % 97.5 %
treated          2.1  1.95   2.27</code></pre>
</div>
</div>
<div class="fragment">
<p>The hazard ratio is close to the true value of 2.</p>
</div>
</section>
<section id="cox-observational-unadjusted" class="slide level2">
<h2>Cox: Observational, Unadjusted</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="" aria-hidden="true" tabindex="-1"></a>bleed_time <span class="ot">&lt;-</span> <span class="fu">rexp</span>(n, <span class="at">rate =</span> <span class="fl">0.1</span> <span class="sc">*</span> <span class="dv">2</span><span class="sc">^</span>obs<span class="sc">$</span>treated <span class="sc">*</span></span>
<span id="cb32-2"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">exp</span>(<span class="fl">0.05</span> <span class="sc">*</span> (obs<span class="sc">$</span>age <span class="sc">-</span> <span class="dv">60</span>) <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> obs<span class="sc">$</span>male))</span>
<span id="cb32-3"><a href="" aria-hidden="true" tabindex="-1"></a>censor_time <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">5</span>)</span>
<span id="cb32-4"><a href="" aria-hidden="true" tabindex="-1"></a>obs<span class="sc">$</span>time <span class="ot">&lt;-</span> <span class="fu">pmin</span>(bleed_time, censor_time)</span>
<span id="cb32-5"><a href="" aria-hidden="true" tabindex="-1"></a>obs<span class="sc">$</span>event <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(bleed_time <span class="sc">&lt;=</span> censor_time)</span>
<span id="cb32-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="" aria-hidden="true" tabindex="-1"></a>fit_cox_naive <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, event) <span class="sc">~</span> treated, <span class="at">data =</span> obs)</span>
<span id="cb32-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">hazard_ratio =</span> <span class="fu">coef</span>(fit_cox_naive), <span class="fu">confint</span>(fit_cox_naive))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        hazard_ratio 2.5 % 97.5 %
treated         3.21     3   3.44</code></pre>
</div>
</div>
<div class="fragment">
<p>The unadjusted hazard ratio is 3.21. The true value is 2.</p>
</div>
</section>
<section id="cox-observational-adjusted" class="slide level2">
<h2>Cox: Observational, Adjusted</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="" aria-hidden="true" tabindex="-1"></a>fit_cox_adj <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, event) <span class="sc">~</span> treated <span class="sc">+</span> age <span class="sc">+</span> male, <span class="at">data =</span> obs)</span>
<span id="cb34-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">hazard_ratio =</span> <span class="fu">coef</span>(fit_cox_adj), <span class="fu">confint</span>(fit_cox_adj))), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        hazard_ratio 2.5 % 97.5 %
treated         2.11  1.96   2.27
age             1.05  1.05   1.05
male            1.59  1.48   1.70</code></pre>
</div>
</div>
<div class="fragment">
<p>After adjustment, the hazard ratio is 2.11.</p>
</div>
</section>
<section id="summary" class="slide level2">
<h2>Summary</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 13%">
<col style="width: 21%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 27%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Treatment effect</th>
<th style="text-align: right;">Truth</th>
<th style="text-align: right;">Trial</th>
<th style="text-align: right;">Observational, unadjusted</th>
<th style="text-align: right;">Observational, adjusted</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Linear (OLS)</td>
<td style="text-align: left;">Difference in means</td>
<td style="text-align: right;">−5.00</td>
<td style="text-align: right;">−5.13</td>
<td style="text-align: right;">1.81</td>
<td style="text-align: right;">−4.93</td>
</tr>
<tr class="even">
<td style="text-align: left;">Logistic</td>
<td style="text-align: left;">Odds ratio</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">1.96</td>
<td style="text-align: right;">3.61</td>
<td style="text-align: right;">2.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Poisson</td>
<td style="text-align: left;">Rate ratio</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">1.48</td>
<td style="text-align: right;">2.08</td>
<td style="text-align: right;">1.51</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cox</td>
<td style="text-align: left;">Hazard ratio</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">2.10</td>
<td style="text-align: right;">3.21</td>
<td style="text-align: right;">2.11</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>In every model, the unadjusted estimate from observational data is biased. Adjusting for the confounders recovers the true effect.</p>
</section></section>
<section>
<section id="from-two-confounders-to-thousands" class="title-slide slide level1 center">
<h1>From Two Confounders to Thousands</h1>

</section>
<section id="the-problem-with-real-data" class="slide level2">
<h2>The Problem With Real Data</h2>
<p>In the simulations, there were two confounders, and we knew what they were.</p>
<p>In OMOP data, each patient can have thousands of recorded conditions, drugs, procedures, and measurements. Any of them might be a confounder. Adding thousands of covariates to an outcome model is difficult to do well.</p>
</section>
<section id="propensity-scores-a-preview" class="slide level2">
<h2>Propensity Scores: A Preview</h2>
<p>A <strong>propensity score</strong> is the probability that a patient receives the treatment, given their covariates.</p>
<ul>
<li>Patients with similar propensity scores have similar covariates, on average.</li>
<li>Matching treated and untreated patients on the score produces groups that are comparable at baseline, as in a trial.</li>
<li>The outcome model can then compare the matched groups directly, without adding the covariates.</li>
</ul>
</section>
<section id="what-are-we-estimating" class="slide level2">
<h2>What Are We Estimating?</h2>
<p>The <strong>estimand</strong> is the quantity a study sets out to estimate. For a treatment effect, the main question is: the effect <em>in whom</em>?</p>
<ul>
<li><strong>ATE</strong>, the average treatment effect: the effect if <em>everyone</em> were treated versus no one</li>
<li><strong>ATT</strong>, the average treatment effect in the treated: the effect among patients who actually <em>received</em> the treatment</li>
<li><strong>ATC</strong>, the average treatment effect in the controls: the effect among patients who did <em>not</em> receive it</li>
</ul>
<div class="fragment">
<p>If the treatment works the same for everyone, the three are equal. When the effect differs across patients, and the treated differ from the untreated, they are not.</p>
</div>
</section>
<section id="estimands-and-propensity-scores" class="slide level2">
<h2>Estimands and Propensity Scores</h2>
<p>The estimand follows from how the propensity score is used.</p>
<ul>
<li>Matching each treated patient to an untreated patient estimates the <strong>ATT</strong>. This is the <code>matchit()</code> default.</li>
<li>Matching each untreated patient to a treated patient estimates the <strong>ATC</strong> (<code>estimand = "ATC"</code>).</li>
<li>Weighting the whole sample, or full matching, can estimate the <strong>ATE</strong> (<code>estimand = "ATE"</code>).</li>
</ul>
<div class="fragment">
<p>A caliper drops treated patients with no close match. The estimate then applies to the treated patients who <em>could</em> be matched, which can differ from all treated patients.</p>
</div>
</section>
<section id="regression-hides-its-estimand" class="slide level2">
<h2>Regression Hides Its Estimand</h2>
<ul>
<li>An outcome model like <code>lm(sbp ~ treated + age + male)</code> returns one coefficient for treatment.</li>
<li>If the effect differs across patients, that coefficient is a weighted average of the effect across covariate groups. It gives the most weight to groups where treatment is close to 50/50, which are not the treated, the untreated, or the whole population.</li>
<li>This is true even when the model adjusts for every confounder.</li>
</ul>
<div class="fragment">
<p>Regression <em>can</em> target the ATE or ATT: fit the outcome model, predict each patient’s outcome treated and untreated, and average over the chosen population. That step has to be done on purpose. With propensity scores, the choice is part of the design.</p>
</div>
</section>
<section id="matching-on-the-propensity-score" class="slide level2">
<h2>Matching on the Propensity Score</h2>
<p><code>matchit()</code> estimates each patient’s propensity score from age and sex. It then pairs each treated patient with the untreated patient whose score is closest, so the estimand is the ATT. The <strong>caliper</strong> sets how close two scores must be. Treated patients with no untreated patient within the caliper are dropped.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="" aria-hidden="true" tabindex="-1"></a>matched <span class="ot">&lt;-</span> <span class="fu">matchit</span>(treated <span class="sc">~</span> age <span class="sc">+</span> male, <span class="at">data =</span> obs, <span class="at">caliper =</span> <span class="fl">0.05</span>)</span>
<span id="cb36-2"><a href="" aria-hidden="true" tabindex="-1"></a>matched_obs <span class="ot">&lt;-</span> <span class="fu">match.data</span>(matched)</span>
<span id="cb36-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Patients kept in each group</span></span>
<span id="cb36-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(matched_obs<span class="sc">$</span>treated)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1 
2641 2641 </code></pre>
</div>
</div>
</section>
<section id="age-and-sex-before-matching" class="slide level2">
<h2>Age and Sex Before Matching</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(<span class="fu">cbind</span>(age, male) <span class="sc">~</span> treated, <span class="at">data =</span> obs, <span class="at">FUN =</span> mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treated      age      male
1       0 57.26718 0.4286973
2       1 65.81325 0.6327170</code></pre>
</div>
</div>
<p>The treated group is older and has more men. <code>male</code> is the proportion of men.</p>
</section>
<section id="age-and-sex-after-matching" class="slide level2">
<h2>Age and Sex After Matching</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(<span class="fu">cbind</span>(age, male) <span class="sc">~</span> treated, <span class="at">data =</span> matched_obs, <span class="at">FUN =</span> mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treated      age      male
1       0 63.42086 0.6005301
2       1 63.62097 0.5948504</code></pre>
</div>
</div>
<p>After matching, the two groups have nearly the same average age and share of men.</p>
</section>
<section id="age-distribution-before-and-after-matching" class="slide level2">
<h2>Age Distribution Before and After Matching</h2>

<img data-src="2026-10-07-reach-ps-survival_files/figure-revealjs/balance-plot-1.png" width="960" class="r-stretch"><p>Before matching, the treated patients skew older. After matching, the two age distributions nearly overlap.</p>
</section>
<section id="the-outcome-model-before-matching" class="slide level2">
<h2>The Outcome Model Before Matching</h2>
<p>As a reminder, this is the unadjusted model on the full, unmatched data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">estimate =</span> <span class="fu">coef</span>(fit_ols_naive), <span class="fu">confint</span>(fit_ols_naive)), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            estimate  2.5 % 97.5 %
(Intercept)   141.96 141.68 142.25
treated         1.81   1.30   2.31</code></pre>
</div>
</div>
<div class="fragment">
<p>The estimate is 1.8 mmHg, far from the true effect of −5.</p>
</div>
</section>
<section id="the-outcome-model-after-matching" class="slide level2">
<h2>The Outcome Model After Matching</h2>
<p>The outcome model contains only the treatment.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="" aria-hidden="true" tabindex="-1"></a>fit_ps <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> treated, <span class="at">data =</span> matched_obs)</span>
<span id="cb44-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">estimate =</span> <span class="fu">coef</span>(fit_ps), <span class="fu">confint</span>(fit_ps)), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            estimate  2.5 % 97.5 %
(Intercept)   146.62 146.18 147.07
treated        -4.67  -5.30  -4.05</code></pre>
</div>
</div>
<div class="fragment">
<ul>
<li>The estimate is −4.7 mmHg. The true effect is −5, and the unadjusted estimate was 1.8.</li>
<li>Note that with matching only, and no covariate adjustment, we are able to recover the treatment effect.</li>
</ul>
</div>
</section>
<section id="doubly-robust-estimation" class="slide level2">
<h2>Doubly Robust Estimation</h2>
<p>We now have two ways to handle confounding:</p>
<ul>
<li>A <strong>propensity score model</strong>, which predicts treatment from the covariates</li>
<li>An <strong>outcome model</strong>, which predicts the outcome from treatment and the covariates</li>
</ul>
<p>Either one gives a biased answer if its model is wrong.</p>
<div class="fragment">
<p>A <strong>doubly robust</strong> approach uses both. Its estimate stays unbiased if <em>either</em> model is correct, so the analysis gets two chances to get it right.</p>
</div>
</section>
<section id="a-misspecified-propensity-score" class="slide level2">
<h2>A Misspecified Propensity Score</h2>
<p>Suppose we leave sex out of the propensity score model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="" aria-hidden="true" tabindex="-1"></a>matched_bad <span class="ot">&lt;-</span> <span class="fu">matchit</span>(treated <span class="sc">~</span> age, <span class="at">data =</span> obs, <span class="at">caliper =</span> <span class="fl">0.05</span>)</span>
<span id="cb46-2"><a href="" aria-hidden="true" tabindex="-1"></a>matched_bad_obs <span class="ot">&lt;-</span> <span class="fu">match.data</span>(matched_bad)</span>
<span id="cb46-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(<span class="fu">cbind</span>(age, male) <span class="sc">~</span> treated, <span class="at">data =</span> matched_bad_obs, <span class="at">FUN =</span> mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treated      age      male
1       0 63.76253 0.4169649
2       1 63.86735 0.6481747</code></pre>
</div>
</div>
<div class="fragment">
<p>Age is balanced, but the treated group still has more men.</p>
</div>
</section>
<section id="the-outcome-model-with-the-wrong-score" class="slide level2">
<h2>The Outcome Model With the Wrong Score</h2>
<p>With only the treatment in the outcome model, the leftover imbalance in sex biases the estimate.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="" aria-hidden="true" tabindex="-1"></a>fit_ps_bad <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> treated, <span class="at">data =</span> matched_bad_obs)</span>
<span id="cb48-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">estimate =</span> <span class="fu">coef</span>(fit_ps_bad), <span class="fu">confint</span>(fit_ps_bad)), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            estimate  2.5 % 97.5 %
(Intercept)   146.30 145.87 146.73
treated        -3.98  -4.59  -3.38</code></pre>
</div>
</div>
<div class="fragment">
<p>The estimate is −4.0 mmHg. The true effect is −5.</p>
</div>
</section>
<section id="matching-plus-covariate-adjustment" class="slide level2">
<h2>Matching Plus Covariate Adjustment</h2>
<p>Now we keep the same flawed matches, but adjust for age and sex in the outcome model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="" aria-hidden="true" tabindex="-1"></a>fit_dr <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> treated <span class="sc">+</span> age <span class="sc">+</span> male, <span class="at">data =</span> matched_bad_obs)</span>
<span id="cb50-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">estimate =</span> <span class="fu">coef</span>(fit_dr), <span class="fu">confint</span>(fit_dr)), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            estimate 2.5 % 97.5 %
(Intercept)    99.81 97.69 101.92
treated        -4.91 -5.45  -4.37
age             0.70  0.67   0.74
male            3.70  3.16   4.24</code></pre>
</div>
</div>
<div class="fragment">
<p>The estimate is −4.9 mmHg. The propensity score model was wrong, but the outcome model was right, so the estimate is still close to −5.</p>
</div>
</section>
<section id="many-covariates-few-patients" class="slide level2">
<h2>Many Covariates, Few Patients</h2>
<ul>
<li>In OMOP data, every condition, drug, procedure, and measurement code can become a covariate. CohortMethod routinely builds tens of thousands of them.</li>
<li>Many codes record the same underlying fact. A diagnosis of type 2 diabetes, a metformin prescription, and an HbA1c test all point to diabetes.</li>
<li>For a rare exposure or a small database, there can be fewer patients than covariates.</li>
<li>Ordinary logistic regression cannot estimate a propensity score in that setting.</li>
</ul>
</section>
<section id="simulating-high-dimensional-data" class="slide level2">
<h2>Simulating High-Dimensional Data</h2>
<p>This data set has 500 patients and 1,000 binary codes. Each of 20 underlying conditions is recorded by 50 related codes. Three conditions drive both treatment and blood pressure. The true effect is again −5.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">7</span>)</span>
<span id="cb52-2"><a href="" aria-hidden="true" tabindex="-1"></a>n_patients <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb52-3"><a href="" aria-hidden="true" tabindex="-1"></a>n_conditions <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb52-4"><a href="" aria-hidden="true" tabindex="-1"></a>codes_per_condition <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb52-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="" aria-hidden="true" tabindex="-1"></a>condition <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rbinom</span>(n_patients <span class="sc">*</span> n_conditions, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> <span class="fl">0.25</span>), <span class="at">ncol =</span> n_conditions)</span>
<span id="cb52-7"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># A patient with the condition usually has each related code; others rarely do</span></span>
<span id="cb52-9"><a href="" aria-hidden="true" tabindex="-1"></a>codes <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">seq_len</span>(n_conditions), <span class="cf">function</span>(k) {</span>
<span id="cb52-10"><a href="" aria-hidden="true" tabindex="-1"></a>  prob <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(condition[, k] <span class="sc">==</span> <span class="dv">1</span>, <span class="fl">0.6</span>, <span class="fl">0.02</span>)</span>
<span id="cb52-11"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">matrix</span>(<span class="fu">rbinom</span>(n_patients <span class="sc">*</span> codes_per_condition, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> prob), <span class="at">ncol =</span> codes_per_condition)</span>
<span id="cb52-12"><a href="" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb52-13"><a href="" aria-hidden="true" tabindex="-1"></a>codes <span class="ot">&lt;-</span> <span class="fu">do.call</span>(cbind, codes)</span>
<span id="cb52-14"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(codes) <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">"code_%04d"</span>, <span class="fu">seq_len</span>(<span class="fu">ncol</span>(codes)))</span>
<span id="cb52-15"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-16"><a href="" aria-hidden="true" tabindex="-1"></a>treated <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n_patients, <span class="at">size =</span> <span class="dv">1</span>,</span>
<span id="cb52-17"><a href="" aria-hidden="true" tabindex="-1"></a>                  <span class="at">prob =</span> <span class="fu">plogis</span>(<span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> condition[, <span class="dv">1</span>] <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> condition[, <span class="dv">2</span>] <span class="sc">-</span> condition[, <span class="dv">3</span>]))</span>
<span id="cb52-18"><a href="" aria-hidden="true" tabindex="-1"></a>sbp <span class="ot">&lt;-</span> <span class="dv">130</span> <span class="sc">-</span> <span class="dv">5</span> <span class="sc">*</span> treated <span class="sc">+</span> <span class="dv">8</span> <span class="sc">*</span> condition[, <span class="dv">1</span>] <span class="sc">+</span> <span class="dv">6</span> <span class="sc">*</span> condition[, <span class="dv">2</span>] <span class="sc">-</span> <span class="dv">4</span> <span class="sc">*</span> condition[, <span class="dv">3</span>] <span class="sc">+</span></span>
<span id="cb52-19"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rnorm</span>(n_patients, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb52-20"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-21"><a href="" aria-hidden="true" tabindex="-1"></a>hd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(treated, sbp, codes)</span>
<span id="cb52-22"><a href="" aria-hidden="true" tabindex="-1"></a>ps_formula <span class="ot">&lt;-</span> <span class="fu">reformulate</span>(<span class="fu">colnames</span>(codes), <span class="at">response =</span> <span class="st">"treated"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="a-standard-propensity-score-fails" class="slide level2">
<h2>A Standard Propensity Score Fails</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="" aria-hidden="true" tabindex="-1"></a>fit_ps_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(ps_formula, <span class="at">family =</span> binomial, <span class="at">data =</span> hd)</span>
<span id="cb53-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients that could not be estimated</span></span>
<span id="cb53-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(<span class="fu">coef</span>(fit_ps_glm)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 501</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated propensity scores</span></span>
<span id="cb55-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">range</span>(<span class="fu">fitted</span>(fit_ps_glm)), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0 1</code></pre>
</div>
</div>
<div class="fragment">
<p>With more covariates than patients, the model cannot estimate half its coefficients, and the scores it does produce are pushed to 0 and 1. These scores cannot be used to match patients. <code>matchit()</code> fits this same model by default.</p>
</div>
</section>
<section id="the-lasso" class="slide level2">
<h2>The Lasso</h2>
<ul>
<li>The <strong>lasso</strong> is logistic regression with a penalty on the size of the coefficients.</li>
<li>The penalty shrinks most coefficients to exactly zero. The model keeps only the covariates that help predict treatment.</li>
<li>Cross-validation picks how strong the penalty should be.</li>
<li>Among a cluster of related codes, the lasso tends to keep a few and drop the rest.</li>
<li>CohortMethod fits its propensity scores this way, using a regularized regression package called Cyclops.</li>
</ul>
</section>
<section id="lasso-propensity-scores-in-matchit" class="slide level2">
<h2>Lasso Propensity Scores in <code>matchit()</code></h2>
<p>Setting <code>distance = "lasso"</code> fits the propensity score with the lasso. It uses the glmnet package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="" aria-hidden="true" tabindex="-1"></a>matched_hd <span class="ot">&lt;-</span> <span class="fu">matchit</span>(ps_formula, <span class="at">data =</span> hd, <span class="at">distance =</span> <span class="st">"lasso"</span>, <span class="at">caliper =</span> <span class="fl">0.05</span>)</span>
<span id="cb57-2"><a href="" aria-hidden="true" tabindex="-1"></a>matched_hd_obs <span class="ot">&lt;-</span> <span class="fu">match.data</span>(matched_hd)</span>
<span id="cb57-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(matched_hd_obs<span class="sc">$</span>treated)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
119 119 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="" aria-hidden="true" tabindex="-1"></a>fit_hd <span class="ot">&lt;-</span> <span class="fu">lm</span>(sbp <span class="sc">~</span> treated, <span class="at">data =</span> matched_hd_obs)</span>
<span id="cb59-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="at">estimate =</span> <span class="fu">coef</span>(fit_hd), <span class="fu">confint</span>(fit_hd)), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            estimate  2.5 % 97.5 %
(Intercept)   133.60 131.54 135.66
treated        -5.73  -8.64  -2.82</code></pre>
</div>
</div>
<div class="fragment">
<p>The unadjusted estimate is −1.9 mmHg. After lasso matching, it is −5.7. The true effect is −5.</p>
</div>
</section>
<section id="friday" class="slide level2">
<h2>Friday</h2>
<ul>
<li>The logic of propensity scores in more detail</li>
<li>CohortMethod on OMOP data, using the Eunomia GI bleed example</li>
<li>Diagnostics for checking whether a study can be trusted</li>
<li>Running the same analysis across a data network with Strategus</li>
</ul>
</section>
<section id="questions" class="slide level2">
<h2>Questions?</h2>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>BIDS Bootcamp · REACH and RStudio</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="2026-10-07-reach-ps-survival_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="2026-10-07-reach-ps-survival_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>